# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14dsWCbu6HTk5EFpdywTu0Ti8MFP12WVm
"""
import pickle
import pandas as pd
df = pd.read_csv('convertcsv.csv')
print(df)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Assuming the first three columns are features and the fourth column is the target
X = df.iloc[:, :3]
y = df.iloc[:, 3]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# prompt: create input to predict

# Assuming the features are numerical
a = int(input("Enter a value for a: "))
b = int(input("Enter a value for b: "))
c = int(input("Enter a value for c: "))

# Make the prediction

new_data_point = [[a, b, c]]
prediction = knn.predict(new_data_point)
print("Prediction:", prediction)
pickle_out = open("model.pkl", "wb")
pickle.dump(knn, pickle_out)
pickle_out.close()